# Generated by Django 3.2.6 on 2022-09-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'app_event',
            },
        ),
    ]
