# Generated by Django 3.2.6 on 2021-10-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        ('favorites', '0002_rename_folder_id_favorite_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='folders.folder'),
        ),
    ]
