# Generated by Django 4.1.5 on 2023-03-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favorites", "0006_alter_favorite_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
