# Generated by Django 4.1.5 on 2024-06-30 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("favorites", "0007_alter_favorite_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorite",
            name="login",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="passkey",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="root",
        ),
    ]
