# Generated by Django 5.2.8 on 2026-02-18 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0008_remove_favorite_login_remove_favorite_passkey_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
