# Generated by Django 3.2.6 on 2021-10-14 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_alter_note_folder_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="folder_id",
            new_name="folder",
        ),
    ]
