# Generated by Django 3.2.6 on 2021-10-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_rename_folder_id_note_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="subject",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
