# Generated by Django 5.2.8 on 2026-02-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0008_alter_note_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_encrypted",
            field=models.BooleanField(default=False),
        ),
    ]
