# Generated by Django 3.2.6 on 2021-10-14 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_folder_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="folder_id",
            new_name="folder",
        ),
    ]
