# Generated by Django 5.2.8 on 2026-02-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_task_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
