# Generated by Django 5.2.8 on 2026-02-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_task_completed_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reminder_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
