# Generated by Django 3.2.6 on 2021-10-14 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_contact_folder_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="folder_id",
            new_name="folder",
        ),
    ]
