# Generated by Django 4.1.5 on 2023-03-07 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_preferences"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="preferences",
            new_name="settings",
        ),
    ]
