# Generated by Django 3.2.6 on 2021-09-03 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210903_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='google_token',
            new_name='google_credentials',
        ),
    ]
