# Generated by Django 4.1.5 on 2023-03-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_preferences_customuser_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="theme",
            field=models.TextField(blank=True, default=""),
        ),
    ]
