# Generated by Django 4.1.5 on 2023-03-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="search_engine",
            field=models.TextField(blank=True, default="google"),
        ),
    ]
