# Generated by Django 4.1.5 on 2023-03-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_customuser_contacts_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tasks_active_folder",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="tasks_folders",
            field=models.JSONField(default=list),
        ),
    ]
