# Generated by Django 4.1.5 on 2023-03-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_customuser_tasks_active_folder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="home_events_hidden",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="home_tasks_hidden",
            field=models.DateField(null=True),
        ),
    ]
