# Generated by Django 4.1.5 on 2023-03-13 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_customuser_home_events_hidden_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="settings",
        ),
    ]
