# Generated by Django 4.1.5 on 2023-03-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_remove_customuser_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tasks_folder",
            field=models.IntegerField(default=0),
        ),
    ]
