# Generated by Django 4.2.11 on 2025-11-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_customuser_tasks_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="home_due_tasks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="home_due_tasks_hidden",
            field=models.DateField(null=True),
        ),
    ]
