# Generated by Django 4.2.11 on 2025-11-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_add_home_due_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="home_due_tasks_hidden",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="home_events_hidden",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="home_tasks_hidden",
            field=models.DateField(blank=True, null=True),
        ),
    ]
