# Generated by Django 4.2.11 on 2025-11-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_add_blank_to_hidden_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sms_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
