# Generated by Django 4.2.11 on 2025-11-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_customuser_phone_number_customuser_sms_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="extension_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
