# Generated by Django 5.2.8 on 2025-12-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_add_extension_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="expanded_folders",
            field=models.JSONField(default=dict),
        ),
    ]
