# Generated by Django 5.2.8 on 2026-02-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_clear_expanded_folders_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="expanded_folders",
        ),
    ]
