# Generated by Django 5.2.8 on 2026-02-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_remove_customuser_expanded_folders"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="encryption_salt",
            field=models.CharField(blank=True, default="", max_length=44),
        ),
    ]
