# Generated by Django 5.2.8 on 2026-02-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_remove_jay_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_reminders",
            field=models.BooleanField(default=True),
        ),
    ]
