# Generated by Django 5.2.8 on 2026-02-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_customuser_email_reminders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email_reminders",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="sms_notifications",
            field=models.BooleanField(default=False),
        ),
    ]
