# Generated by Django 5.2.8 on 2026-02-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_customuser_email_reminders_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="notification_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
