# Generated by Django 3.2.6 on 2021-10-20 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0002_alter_folder_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="folder",
            old_name="user_id",
            new_name="user",
        ),
    ]
