# Generated by Django 4.1.5 on 2023-03-15 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("folders", "0003_rename_user_id_folder_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="editors",
            field=models.ManyToManyField(
                related_name="folder_editors", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
