# Generated by Django 4.2.11 on 2025-08-17 16:23

from django.db import migrations, models
import django.db.models.deletion


def remove_parent_column_if_exists(apps, schema_editor):
    """Remove the parent_id column and any associated foreign key constraints."""
    with schema_editor.connection.cursor() as cursor:
        # Check if parent_id column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'app_folder' AND column_name = 'parent_id'
        """)
        if cursor.fetchone():
            # Drop foreign key constraint first (if it exists)
            try:
                cursor.execute("""
                    SELECT constraint_name 
                    FROM information_schema.table_constraints 
                    WHERE table_name = 'app_folder' 
                    AND constraint_type = 'FOREIGN KEY'
                    AND constraint_name LIKE '%parent%'
                """)
                constraint_names = cursor.fetchall()
                for (constraint_name,) in constraint_names:
                    cursor.execute(f'ALTER TABLE app_folder DROP CONSTRAINT IF EXISTS {constraint_name}')
            except Exception:
                pass  # Constraint might not exist or have different name
            
            # Drop the column
            cursor.execute('ALTER TABLE app_folder DROP COLUMN IF EXISTS parent_id')


def reverse_remove_parent_column(apps, schema_editor):
    """Reverse operation - recreate parent_id column."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE app_folder ADD COLUMN parent_id bigint;
            ALTER TABLE app_folder ADD CONSTRAINT app_folder_parent_id_fkey 
            FOREIGN KEY (parent_id) REFERENCES app_folder(id);
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0004_folder_editors_alter_folder_user"),
    ]

    operations = [
        migrations.RunPython(
            remove_parent_column_if_exists,
            reverse_remove_parent_column,
        ),
    ]
