# Generated by Django 4.2.11 on 2025-07-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0004_folder_editors_alter_folder_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="folders.folder",
            ),
        ),
    ]
