# Generated by Django 5.2.8 on 2026-02-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0007_flatten_folders_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folder",
            name="depth",
        ),
        migrations.RemoveField(
            model_name="folder",
            name="parent",
        ),
        migrations.DeleteModel(
            name="UserFolderPosition",
        ),
    ]
